### ISSUE TITLE
Invalid crop rectangle: [0, -473, 360, 473]

### ISSUE THREAD

**Issue by sibelius** [alexmngn/react-native-image-crop#7]
I think we should validate the crop square before calling ImageEditor before here: https://github.com/alexmngn/react-native-image-crop/blob/master/index.js#L294

```jsx
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Invalid crop rectangle: [0, -473, 360, 473]
       at com.facebook.react.modules.camera.ImageEditingManager$CropTask.<init>(ImageEditingManager.java:222)
       at com.facebook.react.modules.camera.ImageEditingManager$CropTask.<init>(ImageEditingManager.java:199)
       at com.facebook.react.modules.camera.ImageEditingManager.cropImage(ImageEditingManager.java:189)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by alexmngn** [comment]
How did you end up with this error?

**Comment by sibelius** [comment]
this was catch by Fabric Crashlytics, I'll add a condition to make sure the crop square is valid

**Comment by sibelius** [comment]
fixed added a try catch
```jsx
try {
      const imageUri = await this.imageCrop.crop();
    } catch (err) {
      Alert.alert('Error', 'Error on cropping');
    }
```

tks

**Comment by sachins-zluck** [comment]
This is still happening...above solutions didn't worked for me.

**Comment by alexmngn** [comment]
This lib isn't maintained anymore.
